apiVersion: v1
kind: Namespace
metadata:
  name: upload-service
  labels:
    app.kubernetes.io/name: upload-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: file-management-system
    environment: production
