apiVersion: v1
kind: Service
metadata:
  name: upload-service
  namespace: upload-service
  labels:
    app.kubernetes.io/name: upload-service
    app.kubernetes.io/component: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true" # For AWS internal LB
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app: upload-service
