apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: upload-service

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: your-registry/upload-service
    newTag: dev

replicas:
  - name: upload-service
    count: 1
